### ISSUE TITLE
package.json module的路径好像不对

### ISSUE THREAD

**Issue by iwusong** [DataV-Team/DataV-Vue3#31]
![image](https://user-images.githubusercontent.com/44260795/220302285-d3734152-effc-4b61-8218-5562b3d8e3d5.png)
     
文档在这    

![image](https://user-images.githubusercontent.com/44260795/220301953-b53687e2-3829-4b03-8d29-45f37538f079.png)    

    
    
我这样才能正常    
![image](https://user-images.githubusercontent.com/44260795/220302595-ea8b235b-858d-4163-8e98-6639994dfbb3.png)    
    

我的node是  v16.13.2  vite是 4.1.3

**Comment by qindongxu-cn** [comment]
改dataV的 module不治本啊，项目的node_modules是根据版本下载的， 还有啥更有效的方法吗？

**Comment by iwusong** [comment]
> 改dataV的 module不治本啊，项目的node_modules是根据版本下载的， 还有啥更有效的方法吗？

目前，npm上发布的和git代码上的版本也不一致，npm上的代码入口也没有导出为vue插件，不能使用use，还有入口文件错误的问题。要用的话就只能自己打包git上的代码版本，修改入口文件，自己上传到npm上自己用
