### ISSUE TITLE
入坑就错，期待更新

### ISSUE THREAD

**Issue by mymaizi** [DataV-Team/DataV-Vue3#32]
版本如下：
"vue": "3.2.45"    
"vite": "3.2.3"
 "@dataview/datav-vue3": "^0.0.0-test.1672506674342"

Internal server error: Failed to resolve entry for package "@dataview/datav-vue3". The package may have incorrect main/module/exports specified in its package.json.

**Comment by mymaizi** [comment]
#29 #25 #31

**Comment by JMult** [comment]
【1】报错提示
Failed to resolve entry for package "@dataview/datav-vue3". The package may have incorrect main/module/exports specified in its package.json.

将 @dataview\datav-vue3/package.json 文件里的 module项index.js改为index.mjs

// "module": "./es/index.js", //修改前
"module": "./es/index.mjs", // 修改后
